### ISSUE TITLE
Message not found

### ISSUE THREAD

**Issue by dcdruck** [klinker41/android-smsmms#104]
I'm not sure if this is a pulse issue or a phone/network issue to be honest, but over the past two weeks, I've started getting some erroneous incoming messages. A message will come in except it will just read 'Message not found' when I go to view it. It will have a date stamp, but no sender. I have no way of knowing what's at fault or if they're real messages that I'm missing or some kind of phantom messages. They appear the same in the default Android Messages as well as EvolveSMS, but since Pulse is my default, I suspect it first.

**Comment by klinker24** [comment]
How often has it happened? It doesn't seem like this library is generating that message: https://github.com/klinker41/android-smsmms/search?utf8=%E2%9C%93&q=Message+not+found

Does it just open a new conversation, with no title/phone numbers?

**Comment by dcdruck** [comment]
I agree, I don't necessarily think it's Pulse's fault, just seemed like the most obvious place to start being that's it my default SMS handler. It's happened four times since 8/25: once 8/25, once 8/26, twice today (8/28).

They all end up in the same thread that has no sender details. If I go into Messages app and look, they're in a thread titled 'Unknown sender'. Also in Messages app, if I look at the details of one such message: Type='Multimedia message', From='Hidden sender address', Size=17B

**Comment by klinker24** [comment]
So I found a few cases of this, for T-Mobile and AT&T:

https://www.reddit.com/r/tmobile/comments/361s0m/message_not_found_how_do_i_fix_this/
https://forums.att.com/t5/Data-Messaging-Features-Internet/Message-not-found/td-p/3930048

May be a carrier issue, or something intermittent? Unfortunately I am not seeing much on the solution side here...

**Comment by dcdruck** [comment]
Good enough for me. I'm on AT&T, so I'll explore other avenues to try to get to the bottom of it. Thanks for the assist!
