### ISSUE TITLE
Mms receiver - handle sending status.

### ISSUE THREAD

**Issue by SonNgocHoang** [klinker41/android-smsmms#105]
I'm using this library for sending Mms message. But i can't handle when Mms is sent or failed on
MyMms Receiver  extends MmsSentReceiver through intent. How i can handle this?. Thanks you very much.

**Comment by klinker24** [comment]
Adding [this](https://github.com/klinker41/android-smsmms/blob/master/sample/src/main/AndroidManifest.xml#L71) to your manifest will have the library handle the sent status for you. 

You can also extend this class or create your own `BroadcastReceiver` if you need to do something different. That [MmsSentReceiver](https://github.com/klinker41/android-smsmms/blob/master/library/src/main/java/com/klinker/android/send_message/MmsSentReceiver.java) class has all of the logic in it to find which message was sent

**Comment by SonNgocHoang** [comment]
Fisrt : Many thanks for your greats job and very helpful.
But i think you didn't understand my question.
I can receive when message is totaly send to the network. But after that, if the network return failed or success. How i can handle this?. Or just show me a way to do this. Thanks you very much.

**Comment by klinker24** [comment]
I must not understand your question no... 

The `MmsSentReceiver` that I pointed you to handles the sending status of the message. So once your carrier broadcasts back to Android that that message has been "sent", that is the receiver that you should use. There is a similar one for MMS failures: 

```xml
<receiver android:name=".receiver.MmsErrorReceiver"
    android:taskAffinity="com.klinker.android.send_message.MMS_ERROR" />
<receiver android:name="com.klinker.android.send_message.MmsSentReceiver"
    android:taskAffinity="com.klinker.android.messaging.MMS_SENT" />
```

**Comment by SonNgocHoang** [comment]
This is first time in my codelife has anyone response my problem so fast like this. Thank you very much. Hope you have a nice day. :)

**Comment by PradeepAmradi** [comment]
hey @klinker24
There is not such MmsErrorReceiver as per the latest lib version 5.1.4
Is this migrated to MmsReceivedReceiver? could you direct me on handling MMS failures.
