### ISSUE TITLE
Receive information when SMS was sent

### ISSUE THREAD

**Issue by ikurek** [klinker41/android-smsmms#106]
I need to send multiple messages at once, one by one. What I want to, is to receive information, when one message is sent, so I can start sending another one. Is it possible with this library? I saw a way to register a receiver for SMS_SENT, but I have no idea how get and handle the result.

**Comment by klinker24** [comment]
The library has a `SentReceiver` built in to it, that can manage marking messages in the internal database as "Sent": https://github.com/klinker41/android-smsmms/blob/master/library/src/main/java/com/klinker/android/send_message/SentReceiver.java

If you want to do something custom with that receiver (such as send a new message), you should override that `SentReceiver` and provide your custom functionality. You can use it as an example of how to handle the result.

If you declare the receiver in the `AndroidManifest.xml` as described in the readme, this receiver will automatically get called, when the message is sent:

```xml
<receiver
    android:name="com.klinker.android.send_message.SentReceiver"
    android:taskAffinity="[insert package name here].SMS_SENT"/>
```

You can also explicitly tell the library which broadcast receiver to call, when the message gets marked as sent, using the [Transaction#setExplicitBroadcastForSentSms](https://github.com/klinker41/android-smsmms/blob/6b4d0277a7674c4c70915b7c1bf2fcd23f03566c/library/src/main/java/com/klinker/android/send_message/Transaction.java#L150) function.
