### ISSUE TITLE
Can't build APK with Proguard with build SDK 26

### ISSUE THREAD

**Issue by Gaket** [klinker41/android-smsmms#109]
Hi!

We can't build APK using Proguard, we get these warnings:
```
Warning: com.android.mms.transaction.TransactionService: can't find referenced method 'int startUsingNetworkFeature(int,java.lang.String)' in library class android.net.ConnectivityManager
Warning: com.android.mms.transaction.TransactionService: can't find referenced method 'int stopUsingNetworkFeature(int,java.lang.String)' in library class android.net.ConnectivityManager
...
Warning: there were 2 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
```

Tried with versions 4.2.1, 4.2.2. Usual build (using Run button) works well, I think we have different Proguard rules for them.

**Comment by LoungeKatt** [comment]
They removed those methods from the SDK. They still exist in the system, but are no longer accessible to apps that build with API 26+. You can build with SDK 25 or less or you could use a helper class in a small library that you build for SDK 25 and reference in your project. The actual fix involves methods that significantly change the functionality.

**Comment by Gaket** [comment]
Thank you. We've stopped this project but we can return to it later. Closing the issue for now.
