### ISSUE TITLE
Sent MMS messages don't appear in default message application (Hangouts, KitKat)

### ISSUE THREAD

**Issue by patman1** [klinker41/android-smsmms#11]
Exception is thrown in createPartImage(..), somewhere around:
OutputStream os = context.getContentResolver().openOutputStream(res);
ByteArrayInputStream is = new ByteArrayInputStream(imageBytes);. 

Is this lib supposed to work on KitKat? Tried on nexus 5, but got this error.

**Comment by klinker24** [comment]
Any apps using this library will have to be set as the default MMS app, yes. Otherwise, it cannot write to the database
