### ISSUE TITLE
How to be notified on failure?

### ISSUE THREAD

**Issue by amadeu01** [klinker41/android-smsmms#111]
Hi,
I would like to know if it is possible to be notified on failure, like use has no credit to send sms. Or, impossible to send SMS. Or, something like "should retry", "retry first time".

I noticed that there is "NOTIFY_SMS_FAILURE" on RetryScheduler. But, can it be used outside the lib?

**Comment by klinker24** [comment]
For SMS, you can do this inside the receiver for when a message gets sent: https://github.com/klinker41/android-smsmms/blob/master/library/src/main/java/com/klinker/android/send_message/SentReceiver.java#L63

For MMS, you should define an error handler receiver: 

```xml
<receiver
    android:name=".receiver.MmsErrorReceiver"
    android:taskAffinity="com.klinker.android.send_message.MMS_ERROR" />
```

In the receiver's onReceive method, you are basically just provided the stack trace and you can use it to determine the issue.

```java
String stack = intent.getStringExtra("stack");

if (stack.contains("over size limit") || stack.contains("large")) {
    // Message content is too large to send, carrier declined.
} else if (stack.contains("recipients")) {
    // Too many recipients, carrier declined.
} else {
    // handle other cases
}
```

**Comment by amadeu01** [comment]
@klinker24 Thanks
