### ISSUE TITLE
QUESTION: How do I get my message was sent?

### ISSUE THREAD

**Issue by amadeu01** [klinker41/android-smsmms#112]
I send a SMS like this:
```
  private Transaction initSmsTransaction() {
        initSettings();
        Settings sendSettings = new Settings();
        sendSettings.setUseSystemSending(true);
        sendSettings.setDeliveryReports(true);

        Transaction transaction = new Transaction(this, sendSettings);

        transaction.setExplicitBroadcastForDeliveredSms(
                SmsDeliveredReceiver.getIntent(this)
        );
        transaction.setExplicitBroadcastForSentSms(
                SmsSentReceiver.getIntent(this)
        );

        return transaction;
    }

    private void sendSMS(String textMessage, String phoneNumber){
        Transaction transaction = initSmsTransaction();
        Message message = new Message(textMessage, phoneNumber);
        transaction.sendNewMessage(message, Transaction.NO_THREAD_ID);
    }
```

When I send two messages like:

```
sendSMS("Text", "+144444444444") ; // SMS 1

sendSMS("Text", "+144444444444") ; // SMS 2

```
Both messages are equal and they are going to the same phone number. When I get the delivery or sent intent on `SmsDeliveredReceiver` or `SmsSentReceiver`, how do I know if I'm receiving SMS 1 or SMS 2 feedback?

Thanks in advance 😄

**Comment by klinker24** [comment]
The `Intent` that starts your broadcast will have a `message_uri` extra in it. You can use this URI to determine which message is being marked as sent. For an example, you can look at how it works in the library's [SentReceiver](https://github.com/klinker41/android-smsmms/blob/master/library/src/main/java/com/klinker/android/send_message/SentReceiver.java#L37):

**Comment by amadeu01** [comment]
@klinker24 but, is that `message_uri` generated after the message being sent?
Like, how could I know that the `message_uri` I'm receiving in SentReceiver is from `SMS 1` or `SMS 2`

Sorry for that silly questions, but I really did not understand how does it work

**Comment by klinker24** [comment]
I don't really understand your question. The uri points to whichever message is sent. If you look at the `SentReceiver` code that I linked, you will see that the receiver is marking that uri as sent, in the internal database. So it is marking SMS 1 or SMS 2 as sent.

If you need to know more about the message that is being marked as sent, you can query that uri. That could give you the body text, timestamp, who it is to, or whatever you need. That uri just points to the message in the database.

```kotlin
context.contentResolver.query(uri, projection, null, null, sortOrder)
```

**Comment by amadeu01** [comment]
Sorry for the misunderstanding.

What I want to know is:

Given a message P to the number B whit body "XX" - Let's call it  SMS_1
Given a message T to the number  B whit body "XX" - Let's call it SMS_2

I send SMS_1 and SMS_2. 

On my SentReceiver, I receive an intent telling that some message was sent. At this point, I have the `message_uri` that was inside the intent that I have just received. But, when I send the SMS_1 and SMS_2 I did not have those `message_uri`, so how do I know that the `message_uri` I'm retrieving on SentReceiver belongs to SMS_1 or SMS_2. When an intent comes to SentReicever that `message_uri` could represent any message that was sent previously.

Like, If I send 10 equals SMS, but for each SMS I have an internal ID. Even though they are equal, they have different ID from each other. When I receive an intent on `SentReceiver` all body and address from the messages are equal, so I cannot tell if my message was the message with ID 1 or ID 10.

Like, could I do something like `sendSms(myMessage, withURI)`, then I receive something on SentReceiver, I know that these `message_uri` belongs to `myMessage`.

**Comment by klinker24** [comment]
You would need to store the ids for those SMS messages and match them with the `message_uri` that comes in.

**Comment by amadeu01** [comment]
But, when the `onReceive ` in the SentReceiver is called, how do you know which message the intent is representing?

**Comment by klinker24** [comment]
The `message_uri` contains the id for the message. It has everything you need. You can just query that uri to get any information on which message the intent represents, as demonstrated above, in my code that queries the content provider.

**Comment by amadeu01** [comment]
I guess I could not express my doubt really well.

Like, today for matching the SMS that I sent, I check for any SMS I sent that has the same address number and the same SMS body message.

Like this:
```java
private Transaction initSmsTransaction() {
        initSettings();
        Settings sendSettings = new Settings();
        sendSettings.setUseSystemSending(true);
        sendSettings.setDeliveryReports(true);
        Transaction transaction = new Transaction(this, sendSettings);
        transaction.setExplicitBroadcastForDeliveredSms(
                SmsDeliveredReceiver.getIntent(this)
        );
        transaction.setExplicitBroadcastForSentSms(
                SmsSentReceiver.getIntent(this)
        );

        return transaction;
    }

    private void sendSMS(String textMessage, String phoneNumber){
        Transaction transaction = initSmsTransaction();
        Message message = new Message(textMessage, phoneNumber);
        transaction.sendNewMessage(message, Transaction.NO_THREAD_ID);
    }

    public void sendMessage(String textMessage, String phoneNumber, Integer alertRemoteId) {
        try {
            saveAlert(alertRemoteId, textMessage, phoneNumber);
            sendSMS(textMessage, phoneNumber);
        } catch (Exception exception) {
            Timber.e(exception);
            App.logException(exception);
        }
    }
```

```java
public class SmsSentReceiver extends BroadcastReceiver {

    public SmsSentReceiver() {}

    static public Intent getIntent(Context context) {
        return new Intent(context, SmsSentReceiver.class);
    }

    @Override
    public void onReceive(Context context, Intent intent) {
        if (intent.getExtras() != null && intent.getExtras().get("uri") != null) {
            Message message = new Message(context, String.valueOf(intent.getExtras().get("uri")));
            AsyncTaskHandler.notifySentSMS(
                    context,
                    message.getId(),
                    message.getAddress(),
                    message.getBody(),
                    System.currentTimeMillis()
            );
        }
    }
}
```

How do I know the message id when I call `transaction.sendNewMessage`? Then I could compare on 
`SmsSentReceiver`.

Image something like:

```java

  private void sendSMS(String textMessage, String phoneNumber){
        Transaction transaction = initSmsTransaction();
        Message message = new Message(textMessage, phoneNumber);
        long id = transaction.sendNewMessage(message, Transaction.NO_THREAD_ID); // This method return the id of the message that was sent.
    }

```
However what really happens is: the `message_uri` is created at some point after the message is sent and then it notifies to the receiver that is listening to that event. But, in the receiver, I cannot link the sent message to any message that I tried to send because I do not know for sure which message is been represented by the message that just arrived on the receiver.

**Comment by hashirsarwar** [comment]
@amadeu01 did you find any solution? I am having the same problem. Two messages can have same text and addresses. How can we distinguish between them?
