### ISSUE TITLE
Is there any API or Broadcast to know whether MMS is sent correctly or not?

### ISSUE THREAD

**Issue by JuVictor** [klinker41/android-smsmms#119]
First of all, thanking for your perfect library.
But I hope to know whether there is any API or Broadcast to know whether MMS is sent correctly or not.
If yes, I hope to you how to use it and it can distinguish each sending requisition.
For example, I had call the send MMS API 3 times. Then, how I can know 3 MMS are sent correctly or not?

**Comment by klinker41** [comment]
Yes, in fact it is documented right in the readme.

```
<!-- Your custom receiver which is child of com.klinker.android.send_message.MmsSentReceiver -->
<receiver
    android:name="[insert your custom receiver here. eg. com.example.sms_mms.receivers.MyMmsSentReceiver]"
    android:taskAffinity="com.klinker.android.messaging.MMS_SENT"/>
``` 

You can look at the javadocs for MmsSentReceiver for more information.
