### ISSUE TITLE
Receiving MMS sender's phone number

### ISSUE THREAD

**Issue by markandroid2999** [klinker41/android-smsmms#122]
I've been looking at the sample below

```
public class MmsReceiver extends PushReceiver {

}
```

I could see a lot of code in the PushReceiver class, but I can't understand how I can interact with it. For example when someone sends an MMS, I want to be able to get their phone number in the MmsReceiver class. Any help would be highly appreciated.

**Comment by klinker41** [comment]
Push receiver is responsible for saving the message to the internal database, so you'll need to read it from there which can be a bit complicated if you don't already have utils in place to do so.

Extend MmsReceivedReceiver if your app, which exposes a method `onMessageReceived(Uri messageUri)`. Use that message URI to query the message and get whatever data you want from that cursor.

**Comment by markandroid2999** [comment]
I tried doing that but I get an exception when I send my phone a MMS. Should I open a new issue for that? 

Below is what I have when the exception happens.

public class MmsReceiver extends MmsReceivedReceiver {
    private Long conversationId = null;

    @Override
    public void onMessageReceived(Uri messageUri) {

    }
}
