### ISSUE TITLE
Feature: Could accept an Parcelable on sendNewMessage()

### ISSUE THREAD

**Issue by amadeu01** [klinker41/android-smsmms#126]
It would be great to be possible to add extras to the `sentMessageIntent` and `deliveryIntents`

So, one manner of doing that is by passing a `Parcelable` throughout the functions calls, and then the library could add them to their intents.

Then I could be even easier to find out which SMS was sent we the `Receiver` is called. Once the `Parcelable` will come with the intent passed to the `Receivers`

```java
            Intent sentMessageIntent = new Intent(SENT);
            sentMessageIntent.putExtra(SENT_SMS_BUNDLE, message);

            PendingIntent sentIntent = PendingIntent
                    .getBroadcast(mContext, (int) System.currentTimeMillis(), sentMessageIntent,
                            PendingIntent.FLAG_UPDATE_CURRENT);

            Intent delivered = new Intent(DELIVERED);
            delivered.putExtra(DELIVERED_SMS_BUNDLE, message);

            PendingIntent deliveryIntent = PendingIntent
                    .getBroadcast(mContext, (int) System.currentTimeMillis(), delivered,
                            PendingIntent.FLAG_UPDATE_CURRENT);

            sentIntents.add(sentIntent);

            deliveryIntents.add(deliveryIntent);

```

https://github.com/klinker41/android-smsmms/blob/a1a3f91f4481371646ec22421a7d8f1fbba8ddcf/library/src/main/java/com/klinker/android/send_message/Transaction.java#L182

 https://github.com/klinker41/android-smsmms/blob/a1a3f91f4481371646ec22421a7d8f1fbba8ddcf/library/src/main/java/com/klinker/android/send_message/Transaction.java#L118

**Comment by NickM-27** [comment]
This would be a great idea, definitely would help me a lot in making things easier, I might look into making a pull request for this

**Comment by amadeu01** [comment]
@NickM-27 I did a PR for this, if you have the time, I would appreciate you having a look at it.

**Comment by NickM-27** [comment]
@amadeu01 Looks good to me

**Comment by amadeu01** [comment]
@klinker24 could you have a look at the PR? really thanks 😄
