### ISSUE TITLE
Query regarding dual-SIM sending.

### ISSUE THREAD

**Issue by rmukund** [klinker41/android-smsmms#140]
Quick question about dual SIM sending. 
While the subscription id is used to send the message via the selected SIM, it appears like the information is not persisted in the SMS table. Can you please confirm this? Thanks!

**Comment by PradeepAmradi** [comment]
Yes @rmukund, I observed the same.
I have fixed it while receiving MMS
https://github.com/klinker41/android-smsmms/pull/169
Will do the same fix for sending as well.
