### ISSUE TITLE
Accessing hidden method on Oneplus3T Android Pie

### ISSUE THREAD

**Issue by Shani618** [klinker41/android-smsmms#157]
Settings settings = new Settings();
            settings.setMmsc(mmsc);
            settings.setProxy(proxy);
            settings.setPort(port);
            settings.setUseSystemSending(true);
            Transaction transaction = new Transaction(this, settings);
            Message message = new Message("Test", phoneNumber);
            message.setImage(bitmap);
            transaction.sendNewMessage(message, Transaction.NO_THREAD_ID);

Log :

Accessing hidden method Landroid/database/sqlite/SqliteWrapper;->query(Landroid/content/Context;Landroid/content/ContentResolver;Landroid/net/Uri;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)Landroid/database/Cursor; (light greylist, linking)

No idea whats wrong

**Comment by klinker24** [comment]
Nothing is wrong. It is using reflection. Light greylist are the methods that Google does not plan to block.

https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces
