### ISSUE TITLE
"Meet Google Play's target API level requirement" is asking for target API 26

### ISSUE THREAD

**Issue by pdalfarr** [klinker41/android-smsmms#161]
https://github.com/klinker41/android-smsmms/blob/f293e3313ac7d4723d3781b7024d6f3e41a61682/library/build.gradle#L14

says:

  `targetSdkVersion 25`

but 

https://developer.android.com/distribute/best-practices/develop/target-sdk#check_and_update_your_sdks_and_libraries states this:

> Make sure that your **third-party SDK dependencies support API 26**: Some SDK providers publish it in their manifest; others will require additional investigation. If you use an SDK that doesn't support **API 26**, please make it a priority to work with the SDK provider to resolve the issue.

Can android-smsmms comply with this API level requirement?

Thanks

**Comment by pdalfarr** [comment]
I'd like to know if it's safe to use this library regarding this "targetSdkVersion 25 vs 26" thing.

Can someone comment on that?

Thanks.

**Comment by klinker24** [comment]
I use the library in all of my production applications.

**Comment by pdalfarr** [comment]
Great. So I guess this issue can be closed then.
Thanks
