### ISSUE TITLE
What do I put for `threadId` in sendTransaction.sendNewMessage(message, threadId) ?

### ISSUE THREAD

**Issue by DABESTAPPSEVER** [klinker41/android-smsmms#30]
I'm new to Android app development.

in `sendTransaction.sendNewMessage(message, threadId)`, how do I get the value that's supposed to go where `threadId` is?

**Comment by klinker41** [comment]
You can query the conversations on the device and get the id from the conversation you want to send to, or you can pass in Transaction.NO_THREAD_ID and hope for the best.

**Comment by DABESTAPPSEVER** [comment]
If I'm SMS-ing to someone I've never talked to before, would there be a value for `threadId`? If not, should I use `Transaction.NO_THREAD_ID`?

**Comment by klinker41** [comment]
Correct, use no thread id and one will be generated.

**Comment by DABESTAPPSEVER** [comment]
I'm testing my code by sending a text to myself, and my code seems to execute error-free, but I don't get the text.

Here's what I have:

    protected void sendSMSMessage(String phoneNo, String msg){
        try {
            Settings sendSettings = new Settings();
            sendSettings.setSplitCounter(false);
            Transaction sendTransaction = new Transaction(this,sendSettings);
            Message mMessage = new Message(msg,phoneNo);
            mMessage.setType(Message.TYPE_SMSMMS);
            sendTransaction.sendNewMessage(mMessage, Transaction.NO_THREAD_ID);
            Toast.makeText(
                    getApplicationContext(),
                    "SMS sent",
                    Toast.LENGTH_LONG
            ).show();
            Log.v("sendSMSMessage",msg);
        } catch (Exception e) {
            Toast.makeText(
                    getApplicationContext(),
                    "Failed to send. Try again.",
                    Toast.LENGTH_LONG
            ).show();
            e.printStackTrace();
        }
    }

**Comment by DABESTAPPSEVER** [comment]
Any idea what I'm doing wrong?
