### ISSUE TITLE
How does the Lollipop sending work?

### ISSUE THREAD

**Issue by srcreigh** [klinker41/android-smsmms#35]
The main problem is that you can't enabled the MMS network while WiFi is on, right?

I noticed that you're using the new Mms service package (i.e. AOSP/Mms/packages/services). How has this new service helped? You seem to have changed a lot of things.

Side note: the new Mms service package seems to offer a public API for getting carrier MMS settings from the device, which is sweet.

**Comment by srcreigh** [comment]
Why was it important to do the ipv4 vs ipv6 hostname resolution in `MmsRequest`?

**Comment by srcreigh** [comment]
Why are you using `SendRequest` for sending, but not using `DownloadRequest` for receiving? Does `DownloadRequest` not work? If so, why not?

**Comment by klinker41** [comment]
IPv6 was important for T-Mobiles network and will continue to be important in the future more and more as carriers transition over. I don't use download request because I couldn't get it working lol

**Comment by klinker41** [comment]
The biggest benefit for me was that the code was more condensed and easier to understand.
