### ISSUE TITLE
Could not find com.klinkerapps:logger:1.0.3-SNAPSHOT

### ISSUE THREAD

**Issue by JimmyPruitt** [klinker41/android-smsmms#39]
I downloaded the project folder and added it as a dependency to my project in Android Studio, but when the project is syncing I get this error message.

**Comment by klinker41** [comment]
You need to add a snapshot repository to your gradle.build file to get snapshots.

```groovy
allprojects {
    repositories {
        mavenCentral()
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }
}
``

**Comment by jsmale** [comment]
Adding the snapshot repository fixed the first issue for me, but then I got another error after that: 

Gradle sync failed: Could not find android-messaging:phoneutil:unspecified.
           Required by:
           MyApp:app:unspecified > com.klinkerapps:android-smsmms:0.3.0-SNAPSHOT
           Consult IDE log for more details (Help | Show Log)
