### ISSUE TITLE
MMS stucks at sending when sent from the app

### ISSUE THREAD

**Issue by saeedek** [klinker41/android-smsmms#41]
Hello,
I have an issue for sending MMS from the app.it stucks at sending although I have checked the settings with the apn (if I do it manually it gets send no problem there).also the SMS works fine from the app.this is my code for sending MMS:

Settings sendSettings = new Settings();
            sendSettings.setMmsc("http://mms.vodafone.it/servlets/mms");
            sendSettings.setProxy("10.128.224.10");
            sendSettings.setPort("80");
            sendSettings.setGroup(true);
            sendSettings.setDeliveryReports(false);
            sendSettings.setSplit(false);
            sendSettings.setSplitCounter(false);
            sendSettings.setStripUnicode(false);
            sendSettings.setSignature("");
            sendSettings.setSendLongAsMms(true);
            sendSettings.setSendLongAsMmsAfter(3);
            sendSettings.setRnrSe(null);
            Transaction sendTransaction = new Transaction(context, sendSettings);

             Message mMessage = new Message("Code 1","some number");
                        mMessage.setMedia(byteArray,"image/png");
                        mMessage.setType(Message.TYPE_SMSMMS);
                        sendTransaction.sendNewMessage(mMessage, Transaction.NO_THREAD_ID);

**Comment by klinker41** [comment]
You'll have to post the log to see where it is going wrong.

**Comment by saeedek** [comment]
sorry I am a beginner,how can I post the log?

**Comment by saeedek** [comment]
is it possible to set the priority of the MMS to high?

**Comment by saeedek** [comment]
ok the problem was with 1 permission that was not mentioned in the permission list.
the android.permission.WAKE_LOCK
