### ISSUE TITLE
No option to add apn name

### ISSUE THREAD

**Issue by aarajput** [klinker41/android-smsmms#44]
![device-2015-12-01-195521](https://cloud.githubusercontent.com/assets/16102514/11504138/9b010402-9865-11e5-8181-79099605f0d9.png)

I have attatched the image. To send mms , i also need to add this apn name, but there is no option to add apn.

**Comment by klinker41** [comment]
Apn names are not required to send mms messages so far as I've seen in my experience. Android source code does not use them when sending a picture anywhere.
