### ISSUE TITLE
Sample: MMSReceiver class is empty

### ISSUE THREAD

**Issue by Bathilde** [klinker41/android-smsmms#50]
Hello,
I have noticed the MMSReceiver class is empty in the messaging_sample (https://github.com/klinker41/android-smsmms/blob/master/sample/src/main/java/com/klinker/android/messaging_sample/MmsReceiver.java)

**Comment by Bathilde** [comment]
My bad, I did not see it inherits from the PushReceiver class!

**Comment by arya6000** [comment]
@Bathilde I'm stuck on how to use the MMSReceiver class, I do understand that it extends PushReceiver, but not sure how to use it. Can you give me some pointers as what I need to do? I'm trying to get the sender's phone number, and it would be perfect if I can get the image too.
