### ISSUE TITLE
INSTALL_FAILED_CONFLICTING_PROVIDER

### ISSUE THREAD

**Issue by sjellish** [klinker41/android-smsmms#51]
I have been messing around with android-smsmms and found that after the December updates that you added I can no longer install an app I have been writing using the library. I get the error INSTALL_FAILED_CONFLICTING_PROVIDER. After doing some debugging I found that it has to do with the .MmsFileProvider you added. The file provider uses the authority com.klinker.android.messaging.MmsFileProvider.

Now it just so happens that I already had your EvolveSms app installed on my phone. Your app also uses the library and has the file provider and authority. After looking around a bit I found that android:authorities must be unique, so trying to install a second app that uses the library will always fail. Here are a couple links about it.

http://stackoverflow.com/questions/16267785/install-shows-error-in-console-install-failed-conflicting-provider

http://gradlewhy.ghost.io/overcoming-install-failed-conflicting-provider/

If I uninstall EvolveSms then my app will install fine and if I try to re-install EvolveSms after my app is on the phone EvolveSms will fail with a 505 error.

I haven't looked too much into a solution yet, but I think something like the second link might work: have gradle assign a unique authority name based on the app name.

Anyway, your library seems to work really well otherwise, and I haven't been able to find anything else like it out there. So great job. I just don't want people to get frustrated with it when their users try to install their app on a phone that already has an app using the library.

Thanks for all the effort you have put into this.

**Comment by sjellish** [comment]
Found this link: https://code.google.com/p/analytics-issues/issues/detail?id=784

perhaps setting it to 

android:authorities="${applicationId}.messaging.MmsFileProvider"

and having 

android {
    defaultConfig.applicationId = "my.package.id"
}

set in the build.gradle file might fix it.

**Comment by klinker41** [comment]
Thanks, that seems to have solved it (https://github.com/klinker41/android-smsmms/commit/9503bb8669b3ab959a07e0207d4c9e505598ebdf). Will release version 2.3.0 shortly with the fix to maven central.
