### ISSUE TITLE
It can send mms sucessuly,but the picture received is not valid.

### ISSUE THREAD

**Issue by Jibinghao** [klinker41/android-smsmms#57]
Its name is ”image_0.mms”,my phone is android 6.0

**Comment by Jibinghao** [comment]
String filename = p.MimeType.split("/")[0] + "_" + id + ".mms";
Now it's normal. change the JPEG to MMS on it.I don't know what is mms?

**Comment by klinker24** [comment]
@aTakayukiMoria @aTakuyaKaneko

The changes on your fork look very good. If you would like to make a pull request, I would love to review and merge them into this project.

**Comment by klinker24** [comment]
I went ahead and pulled in many of the improvements from the above-mentioned library, this issue should be fixed as one of the changes.
