### ISSUE TITLE
When Target SDK is over 23, this library is crashed and MMS is not sent.

### ISSUE THREAD

**Issue by JuVictor** [klinker41/android-smsmms#58]
If I set the target SDK to over 23 version, this library is crashed and MMS is not sent.
The root cause is using startUsingNetworkFeature and stopUsingNetworkFeature.

startUsingNetworkFeature

Added in API level 1
int startUsingNetworkFeature (int networkType, 
                String feature)
This method was deprecated in API level 21.
Deprecated in favor of the cleaner requestNetwork(NetworkRequest, NetworkCallback) API. In M, and above, this method is unsupported and will throw **UnsupportedOperationException** if called.

stopUsingNetworkFeature

Added in API level 1
int stopUsingNetworkFeature (int networkType, 
                String feature)
This method was deprecated in API level 21.
Deprecated in favor of the cleaner unregisterNetworkCallback(NetworkCallback) API. In M, and above, this method is unsupported and will throw **UnsupportedOperationException** if called.

https://developer.android.com/reference/android/net/ConnectivityManager.html#startUsingNetworkFeature(int, java.lang.String)

**Comment by klinker41** [comment]
Using it in multiple different apps set to 24 and having no issues with either.

**Comment by JuVictor** [comment]
What is mean of "multiple different apps set to 24"?
Could you please explain me it in detail?

**Comment by klinker41** [comment]
I have published multiple apps on the play store that use this library and target api level 24 and both are working correctly.

**Comment by JuVictor** [comment]
Have you ever trying to check it with API Level 23?
I guess API Level 24 might have the same problem.
**In M, and above, this method is unsupported and will throw UnsupportedOperationException if called.**

Or please try to disable MMS Sending and check it with Mobile Data.

**Comment by klinker41** [comment]
Like I just said, I use this library without problem when targeting N and I used it without problem for 6 months targeting M.

**Comment by JuVictor** [comment]
I think you might take the error, if the flow will be as below.

java.lang.UnsupportedOperationException: This method is not supported in target SDK version 23 and above
Utils.ensureRouteToHost()
>
android.net.ConnectivityManager.startUsingNetworkFeature()
>
android.net.ConnectivityManager.checkLegacyRoutingApiAccess()
>
android.net.ConnectivityManager.unsupportedStartingFrom()

**Comment by thomasroulin** [comment]
I have the same problem with the `MmsReceivedReceiver` (did not try with MMS sending yet). When the `MmsReceivedReceiver` call `Utils.ensureRouteToHost` (in the `sendPdu(...)` method) it throws an `InvocationTargetException` which is caused by a :
```
UnsupportedoperationException: This method is not supported in target SDK version 23 and above
``` 

@JuVictor Did you find any work around ?
@klinker41 Have you any idea why your apps targeting M or N works, but not on our devices ?

**Comment by klinker41** [comment]
I don't use this method anymore. I set my apps to use the system sending method.

**Comment by thomasroulin** [comment]
Okay, then may I ask you if you have any lead on how to use the system sending(/receiving ?) methods ? I'm struggling to find any tangible information. Documentation, example, tutorial, everything is welcome.

*PS*: Nevertheless thank you for the API you provide and your quick response.

**Comment by klinker41** [comment]
`Settings#setUseSystemSending`

**Comment by JuVictor** [comment]
If we use this, it will be sent successful  in case of set as default  app. Is it right?

**Comment by klinker41** [comment]
You should be the default app regardless if you are using this library, that is what it is designed for and isn't meant to operate when you aren't. I have no idea what will happen if you aren't the default.

**Comment by ewshadow** [comment]
Hi guys, startUsingNetworkFeature in Transaction service is removed after API 25. Anyone know an alternative for that issue!

**Comment by JuVictor** [comment]
I found the way to send MMS without setting default app almost 1 year ago. Thanks for your support.
