### ISSUE TITLE
Support for retrieving sms history

### ISSUE THREAD

**Issue by tunjos** [klinker41/android-smsmms#59]
Hi @klinker41.
Would you like to have support for retrieving sms history?
This could be specific as well eg Inbox/sent/draft.

**Comment by klinker41** [comment]
Sorry, not the focus of this library, it will only be for sending and receiving. Google has good documentation on how to read sms, you'll have to refer to that to work with it.

**Comment by tunjos** [comment]
I was asking, so I could implement it and send a PR.
No problem, since its not the focus.
Thanks.
