### ISSUE TITLE
How to save MMS and download later?

### ISSUE THREAD

**Issue by themelisx** [klinker41/android-smsmms#65]
Can you help me out on How to save incoming MMS, so I can download later ?
What data needed to start the transaction to download the message?

**Comment by klinker41** [comment]
You'll need to implement this yourself from the [`MmsReceivedReceiver`](https://github.com/klinker41/android-smsmms/blob/master/library/src/main/java/com/klinker/android/send_message/MmsReceivedReceiver.java), it isn't functionality that I'll be adding.
