### ISSUE TITLE
Gradle can't find com.klinkerapps:logger:1.0.3-SNAPSHOT dependency

### ISSUE THREAD

**Issue by cjwilliams24680** [klinker41/android-smsmms#66]
When trying to compile with the latest version (3.4.6), gradle throws an error because it can't find one of the library's dependencies.

**Comment by klinker24** [comment]
We need to take out the SNAPSHOT dependency, but adding this to the top-level build.gradle file will do the trick:

```
allprojects {
    repositories {
        ...
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
}
```

You just need to tell it to look in the snapshot maven central repo.

**Comment by klinker41** [comment]
It will take a few hours to populate to maven to be able to grab, but should be fixed after that.

**Comment by cjwilliams24680** [comment]
that was fast, thanks!
