### ISSUE TITLE
Use System Sending issue

### ISSUE THREAD

**Issue by domestos99** [klinker41/android-smsmms#69]
I have got your code, opened it in Android Studio and in MainActivity just changed **sendSettings.setUseSystemSending(false)**; (to false). 
Then install app to phone (Honor 7 Lite, Android 6) (+ set as default msg app) and sent MMS but it threw an exception android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
in com.android.mms.service_alt.**MmsHttpClient**
at line 176 (final OutputStream out = BufferedOutputStream(connection.getOutputStream());)
Am i missing something or is it common issue? Thx

**Comment by klinker24** [comment]
With android 6.0+, if you aren't using the system sending methods, there are some [permissions](https://github.com/klinker41/android-smsmms/blob/master/upgrading_for_marshmallow.md) that you will need to manage, you will also need to get the correct APNs in there, if you aren't using the system sending method.

**Comment by klinker24** [comment]
Closing due to lack of resolution, assuming that that fixed things for you. Let me know otherwise
