### ISSUE TITLE
Prepare for Android O

### ISSUE THREAD

**Issue by klinker24** [klinker41/android-smsmms#77]
We need to remove all the implicit broadcasts. They are currently used for delivery/sent receivers, as well as MMS received receivers.

Perhaps we could convert these into `IntentServices` that are started by the library? 

I could see some kind of permission being defined in the app's manifest, for each different action. Then, the library will search for that permission and fire up the `IntentService`, rather than broadcast the intent action.

This will need to be a major upgrade to the library (v4.0.0), since current implementations will break.

**Comment by klinker41** [comment]
@klinker24 are we good to call this one working and close now?

**Comment by klinker24** [comment]
Ship it 👍

**Comment by klinker41** [comment]
Ok, deploying version 4.0.0 now.
