### ISSUE TITLE
Number parsing adds extraneous prefix

### ISSUE THREAD

**Issue by LoungeKatt** [klinker41/android-smsmms#81]
When using a number that already includes a 1 but does not include +1, such as 1 (555) 555 - 5555, I end up with an outgoing group conversation to "+1, 1 (555) 555 - 5555"

I have a feeling it may check for +1 or not +1 exclusively, without checking for 1 without a +.

I am still poking around to find out where this happens and if that is the cause, but I am posting this here just in case someone else has already addressed it.

**Comment by klinker41** [comment]
Phone numbers are extremely tricky to handle correctly since they are very different all over the world. Feel free to open a pull request if you track down the solution.

**Comment by LoungeKatt** [comment]
I have to test stripping the number before sending it to the library and if that fixes it, I should have something.

**Comment by LoungeKatt** [comment]
I pushed the pull as https://github.com/klinker41/android-smsmms/pull/82
