### ISSUE TITLE
QUESTION: Does this library handle queuing?

### ISSUE THREAD

**Issue by searchy2** [klinker41/android-smsmms#86]
Just ran the send transaction through a for loop and sent out 30 MMS images successfully on a Android N device. Impressive! The messages were sent using the system method so the phone handles the queuing? 
Does this library handle queuing messages in any way? Thanks for any insight!

Edit: typo :disappointed:

**Comment by klinker41** [comment]
The library does not queue anything, it sends them off when it receives the request.

**Comment by searchy2** [comment]
Thanks for the insight. I'll be developing my own queuing system then! 
Here's what I found about sending multiple messages. Going to leave it here in case others have questions. 

> Using the System Sending method, messages dispatched via Send Transaction send perfectly even when multiple messages are sent in short succession. However, only one broadcast receiver is fired. It seems that even though this library can fire off as many requests as sent, the callbacks and broadcasts are not fast enough to keep up. Therefore, for proper handling of sent messages, querying the MMS database is required or a queuing system needs to be established.

**Comment by celeronpm** [comment]
@searchy2 I use the library in my app as well and have also created a queuing system. I persist the queue to my own repository to handle offline issues (if the app is disconnected, airplane mode, etc..). When connection is re-established, the queue gets expunged. 

This mechanism also has the benefit of being able to introduce throttling. Under slow network speeds, you can be a good guest and throttle the sends accordingly while guaranteeing delivery. Finally, if you persist to disk, you can retry failed sends at your leisure and have durability over restarts, network issues, etc..

**Comment by searchy2** [comment]
@celeronpm Good reasons to create your own queuing! I am doing the same right now by limiting the messages passed to the Send Transaction through the MessageSentReceiver. My very rudimentary queuing system operates on the logic that only when one message has successfully sent and the MessageSentReceiver receives a broadcast, then start the next message. Of course, there is error handling and resuming/skipping messages to be built into that as well. 
There is a quirk I've noticed and I wonder what your solution is. 

> When MMS messages are sent through the Send Transaction, they trigger the MessageSentReceiver even if the sending failed. How do you know if sending messages failed? Are there callbacks in Transaction.java that return failed messages? Thanks for any pointers!

**Comment by celeronpm** [comment]
To he honest, I forked the lib and completely rewrote the callbacks to be more verbose and durable, and to include transaction IDs to help identify the callbacks precisely. This was required since my queue can be expunged over a long period of time (reboots, etc...).

Maybe I'll contribute my changes back into the lib to share the enhancements with the community.
________________________________
