### ISSUE TITLE
Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/android/mms/LogTag.class

### ISSUE THREAD

**Issue by antonio-jimenez** [klinker41/android-smsmms#91]
com/android/mms/LogTag.class

It's producing an error when trying to sign an APK for production. It clashes with other libraries. Just moving the class to another package solves the error

**Comment by klinker41** [comment]
Seems like other libraries you are using are also including that file.

**Comment by antonio-jimenez** [comment]
Indeed. Any idea about how to solve it? I have had to fork the project just to make that change.

**Comment by klinker41** [comment]
You can submit a pull request either moving the class or renaming it.

**Comment by antonio-jimenez** [comment]
Sure, I will!

**Comment by aajn88** [comment]
Do you know when a new version with this fix would be published?

**Comment by klinker41** [comment]
Sometime later today maybe. I don't know.

**Comment by klinker24** [comment]
It should be live within the next half hour or so. v4.0.1

**Comment by aajn88** [comment]
Awesome! Thanks!

**Comment by aajn88** [comment]
Seems like the update hasn't been included into 4.0.1, `LogTag.java` is still under `com.android.mms` and not under `com.android.mms.logs` as appears in master

**Comment by klinker24** [comment]
No, it definitely contained your commit. I can try to push up another version I guess, but it will be the same...

**Comment by aajn88** [comment]
I've decompiled the `.aar` file from here https://mvnrepository.com/artifact/com.klinkerapps/android-smsmms/4.0.1
and I saw that LogTag.java is still under the same folder. Actually, on that URL says that the update was made on April

![screen shot 2017-06-09 at 10 24 15 am](https://user-images.githubusercontent.com/5447552/26982370-d4ec4692-4cfd-11e7-90e1-c43f7af18267.png)

**Comment by klinker24** [comment]
Hmm, maybe we previously released a 4.0.1? I just pushed 4.0.2, so you can try it out and see if it works.

**Comment by aajn88** [comment]
Thanks! I'll keep you informed

**Comment by antonio-jimenez** [comment]
Eureka! Thanks, bud!

**Comment by aajn88** [comment]
Eureka! Thanks, bud!

**Comment by klinker24** [comment]
Glad it worked! We must have had a previous 4.0.1 that I hadn't pushed to GitHub.

**Comment by aajn88** [comment]
Nice! :) still is not visible [https://mvnrepository.com/artifact/com.klinkerapps/android-smsmms](here) I think It'll get refreshed in few hours?

**Comment by klinker24** [comment]
It can be a few days before that gets updated. I have never understood their update schedule there
