### ISSUE TITLE
Read SMS permission bug

### ISSUE THREAD

**Issue by aajn88** [klinker41/android-smsmms#96]
In some Xiaomi devices, TransactionService is being started when the application is launched by the first time after installation. At that point the app wasn't able to request permissions to the user. The lack of enough permissions is resulting in an exception thrown by this service.

I've made a [pull request](https://github.com/klinker41/android-smsmms/pull/95) with a fix proposal.

**Comment by klinker24** [comment]
Thanks, closed with #95.

**Comment by aajn88** [comment]
Awesome! Thanks!
