### ISSUE TITLE
Update OKHTTP to v3.8.1

### ISSUE THREAD

**Issue by searchy2** [klinker41/android-smsmms#97]
Are there any plans to update OKHTTP to the latest version v3.8.1?
The current OKHTTP version used is 2.5.0. Updating directly to 3.8.1 causes errors because the API changed. The reason I propose an update to the latest version is because people might be using the latest version of OKHTTP in their app and having two conflicting versions of the same library is not good. 

I cannot find an upgrade guide so the upgrade might be difficult. Anything I should know before attempting an update?

**Comment by klinker41** [comment]
I have no plans to do this, no. I have not looked into what the difficulties would be, sorry.
