### ISSUE TITLE
What does RCS mean for SMS?

### ISSUE THREAD

**Issue by searchy2** [klinker41/android-smsmms#99]
Came across an interesting article posted today about RCS, the successor to SMS/MMS. Wonder what it will mean for this library. Maybe Google will finally release proper APIs for the new protocol? One can hope :D
https://www.digitaltrends.com/mobile/what-is-rcs-messaging/

**Comment by klinker41** [comment]
I'll just refer you to https://github.com/klinker-apps/messenger-issues/issues/143 for more information.

**Comment by searchy2** [comment]
Thanks :) There's more news about RCS recently so hopefully that means Google is close to releasing something!

**Comment by 2br-2b** [comment]
Since the old link is broken, here's a link to the archived page: https://web.archive.org/web/20201111221326/https://github.com/maplemedia/pulse-sms-issues/issues/143
